spring:
  main:
    lazy-initialization: true
  datasource:
    url: ${DB_URL}
    username: ${DB_USER}
    password: ${DB_PASS}
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: none
  servlet:
    tomcat:
      threads:
        max: 10
    multipart:
      max-file-size: 500MB
      max-request-size: 500MB
      file-size-threshold: 2MB
server:
  tomcat:
    threads:
      max: 5
minio:
  url: ${MINIO_URL}
  accessKey: ${MINIO_ACCESS_KEY}
  secretKey: ${MINIO_SECRET_KEY}
  bucket: ${MINIO_BUCKET}